Repository mohitahlawat2001/calculator-app, pull requests merged in 2023-10, with the labels that each got.

#9 Hover effect
  src/App.css
Labels: enhancement, hacktoberfest

#19 fix: NaN result on toggle negative/positive number
  src/components/Button.js
Labels: hacktoberfest

#34 added history
  package-lock.json
  src/App.css
  src/App.js
  src/components/Button.js
  src/components/History.css
  src/components/History.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#36 Always display history and new input
  src/App.css
  src/App.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#37 fix overflow issue in display section when user put long numbers
  src/App.css
Labels: hacktoberfest-accepted

#42 enhancements in README.md - screenshots and hacktoberfest guide
  README.md
  images/decimal1.png
  images/decimal2.png
Labels: hacktoberfest, hacktoberfest-accepted

#45 Title and icon modified + minor UI enhancement
  public/calculator-icon.ico
  public/index.html
  src/App.css
Labels: hacktoberfest, hacktoberfest-accepted
